# Generated by Django 5.2 on 2025-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_gst_amount_alter_invoice_grand_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_amount', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
