# Generated by Django 5.2 on 2025-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_dailysale'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GPay', 'GPay'), ('Card', 'Card')], default='Cash', max_length=10),
        ),
    ]
