# Generated by Django 5.2 on 2025-05-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.IntegerField(),
        ),
    ]
