# Generated by Django 5.2 on 2025-05-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_dailysale_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='total_items_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.IntegerField(),
        ),
    ]
