# Generated by Django 5.2 on 2025-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_dailysale_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
