# Generated by Django 5.2 on 2025-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
