# Generated by Django 5.2 on 2025-05-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GPay', 'GPay'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
    ]
