# Generated by Django 5.2 on 2025-05-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_payment_method'),
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
    ]
