# Generated by Django 5.2 on 2025-05-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
    ]
