# Generated by Django 5.2 on 2025-06-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
