# Generated by Django 5.2 on 2025-05-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_half_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 0.5kg (only if unit is kg and applicable)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram')], default='pcs', max_length=3),
        ),
    ]
