# Generated by Django 5.2 on 2025-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_half_kg_product_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_half_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
    ]
