# Generated by Django 5.2 on 2025-05-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_quantity_product_price_half_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (Large)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (Medium)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (Small)'),
        ),
    ]
